### ISSUE TITLE
Sample solution should not include project ref but as NuGet package

### ISSUE THREAD

**Issue by ChrisEnglert** [1and1/WebApi.BasicAuth#1]
Hi, in https://github.com/1and1/WebApi.BasicAuth/blob/master/Sample/Sample.csproj
`line 100:     <ProjectReference Include="..\WebApi.BasicAuth\WebApi.BasicAuth.csproj">
`
you include the code as a project... namespaces and assembly names in config are different once you build an application using the code, thus the sample becomes misleading...

e.g.:

```
  <configSections>
    <section name="basicAuth" type="WebApi.BasicAuth.BasicAuthSection" />
  </configSections>
```

should be:

```
  <configSections>
    <section name="basicAuth" type="WebApi.BasicAuth.BasicAuthSection, WebApi.BasicAuth" />
  </configSections>
```

..for an application using it as a NuGet package (since it's referencing another assembly)

**Comment by bastianeicher** [comment]
Fixed in 76f0fb8e
