### ISSUE TITLE
Comparison reversed

### ISSUE THREAD

**Issue by sunil-c** [1and1/WebApi.BasicAuth#2]
In BasicAuthFilers.cs you are encoding the incorrect password string and comparing to the wrong password string. Inside the encode function should be Encoding.UTF8.GetBytes(user.Password) and also hashedPassword should be compared to credentials.Password.ToUpperInvariant() not user.Password

Otherwise it works fine.

Thanks.

**Comment by bastianeicher** [comment]
`credentials` holds non-hashed username + password decoded from Base64 in the `Authorization` header of the incoming HTTP request.
`user` holds the username and (optionally hashed) password loaded from the local configuration file.

Therefore we hash the password sent in the request (`algo.ComputeHash(Encoding.UTF8.GetBytes(credentials.Password))`) and compare it to the expected hash (`user.Password`).

I don't see any problem here?

**Comment by sunil-c** [comment]
I'm just reporting what I see and how it worked when I plugged it into my application. Once I made the change it worked correctly. Have you tried using your code in an application?

**Comment by sunil-c** [comment]
Let's review the code as-is: 

//the password received the credentials object is already 
//hashed and encrypted on the client side - you don't want to do it again here
string hashedPassword = BitConverter.ToString(algo.ComputeHash(Encoding.UTF8.GetBytes(credentials.Password))).Replace("-","");

//here you are comparing the hashed-encrypted-hashed(again) password 
//to the plain text password in the config file -- i don't think that was your intent
if (hashedPassword == user.Password.ToUpperInvariant()) 
  context.Principal = BuildPrincipal(user);

//what you want to do is hash and encrypt the password 
//from the config file and compare it to what the client passes you

**Comment by bastianeicher** [comment]
Perhaps you are accessing the API using a non-standard client?

Citation from Wikipedia article on HTTP Basic Auth:
> The BA mechanism provides no confidentiality protection for the transmitted credentials. They are merely encoded with Base64 in transit, but not encrypted or hashed in any way.

So the client should not be performing any hashing. The hashing is merely an implementation detail of this library to avoid having to save clear-text passwords. It is not an intrinsic part of HTTP Basic Auth.

The solution contains a sample Web API project that uses the library. If you run it and then open this URI in your browser you will see a login prompt: http://localhost:20536/auth
It works with both:
 * user `JohnDoe`, password `abc` (stored hashed in `Web.config`) and 
 * user `JaneDoe`, password `abc` (stored as clear-text in `Web.config`).

**Comment by sunil-c** [comment]
After your last comment I see what I assumed to be the usage to the opposite of what you intended. I was encrypting the the password in the client and storing it plaintext on the server side. I only intended the user name password used in the headers to be a basic authentication mechanism and then a further login screen for obtaining the authentication credentials. TL;DR if you use it the way you intended then I was wrong, use it the way I thought and you need to make the change I suggested.

**Comment by bastianeicher** [comment]
Thanks for the clarification.
